# Generated by Django 3.1.4 on 2020-12-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201213_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_final',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicial',
            field=models.TimeField(),
        ),
    ]
